
class State:
	INSTALLED = 'INSTALLED'
	RESOLVED = 'RESOLVED'
	ACTIVE = 'ACTIVE'
	STOPPING = 'STOPPING'
	STARTING = 'STARTING'
	STOPPED = 'STOPPED'
	RESTARTING = 'RESTARTING'
	UNINSTALLED = 'UNINSTALLED'